### ISSUE TITLE
Uploading files fails

### ISSUE THREAD

**Issue by afischer211** [nextcloud/integration_paperless#17]
Hi there,

thanks for your solution for integrating paperless into nextcloud. Can you extend this solution for supporting paperless-ngx? I tried it with a paperless-ngx instance, but the upload of files fails. Of course I configured url of the instance and a valid token.

**Comment by provokateurin** [comment]
Hi, paperless-ngx is the only version that is supported. I know the name of the integration might be a bit misleading.

Now to the problem itself: Can attach the logs of your server (with loglevel set to 0) and your browser logs when you try the upload?

**Comment by sylanc3** [comment]
Hello @afischer211 ,
how is your Server URL looking?
I specified: "http://192.168.178.6:8000" and the Authorization Token from Paperless.
Also added in NC config.php
`'allow_local_remote_servers' => true,`

Now working under NC29.0.0

**Comment by afischer211** [comment]
I'm using Nextcloud AIO and Paperless-ngx as Docker-containers on the same machine. After adding the https-URL to Paperless to the Nextcloud configuration (without trailing slash!) and adding the config-line to the config.php the solution works in NC28.0.5.
