### ISSUE TITLE
App only compatible with 28+ due to missing method

### ISSUE THREAD

**Issue by miscawelo** [nextcloud/integration_paperless#20]
I'm trying to set up this integration, but when I input the server address and API token I get an internal server error when I try to access my files.

My server setup: I access Nextcloud behind Caddy as a reverse proxy and PiHole for DNS, each one inside a container (the IP in the error belongs to the Caddy container). The Nextcloud container however, has Cloudfare as DNS server so I input the IP address and port in the server URL (without port defined it behaves exactly the same).

I access every service using a subdomain per service, eg. https://nextcloud.domain.local.

Here's the error and relevant log.

![Screenshot_20240509_100415](https://github.com/nextcloud/integration_paperless/assets/83408227/a1b1cd4c-2ac7-43af-a83e-f37d2d683e64)

> {
  "reqId": "F8gEpCBC1FZMFSEH0j7z",
  "level": 3,
  "time": "2024-05-09T15:49:14+00:00",
  "remoteAddr": "X.X.X.X",
  "user": "admin",
  "app": "index",
  "method": "GET",
  "url": "/index.php/apps/files/?dir=/PATH/TO/SOME/FILE&fileid=9579",
  "message": "Exception thrown: Exception",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0",
  "version": "27.1.8.1",
  "exception": {
    "Exception": "Exception",
    "Message": "Call to undefined method OCP\\Util::addInitScript() in file '/var/lib/nextcloud/apps/integration_paperless/lib/Listener/FileActionListener.php' line 27",
    "Code": 0,
    "Trace": [
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php",
        "line": 183,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/base.php",
        "line": 1068,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/index.php",
        "line": 38,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 169,
    "Previous": {
      "Exception": "Error",
      "Message": "Call to undefined method OCP\\Util::addInitScript()",
      "Code": 0,
      "Trace": [
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php",
          "line": 86,
          "function": "handle",
          "class": "OCA\\Paperless\\Listener\\FileActionListener",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
          "line": 251,
          "function": "__invoke",
          "class": "OC\\EventDispatcher\\ServiceEventListener",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php",
          "line": 73,
          "function": "callListeners",
          "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
          "line": 94,
          "function": "dispatch",
          "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/EventDispatcher/EventDispatcher.php",
          "line": 106,
          "function": "dispatch",
          "class": "OC\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/apps/files/lib/Controller/ViewController.php",
          "line": 286,
          "function": "dispatchTyped",
          "class": "OC\\EventDispatcher\\EventDispatcher",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 230,
          "function": "index",
          "class": "OCA\\Files\\Controller\\ViewController",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 137,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php",
          "line": 183,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/Route/Router.php",
          "line": 315,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/base.php",
          "line": 1068,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/index.php",
          "line": 38,
          "function": "handleRequest",
          "class": "OC",
          "type": "::"
        }
      ],
      "File": "/var/lib/nextcloud/apps/integration_paperless/lib/Listener/FileActionListener.php",
      "Line": 27
    },
    "CustomMessage": "Exception thrown: Exception"
  }
}

**Comment by provokateurin** [comment]
> Call to undefined method OCP\Util::addInitScript

This sounds extremely suspicious regarding an outdated server version. What server version are you running?

**Comment by provokateurin** [comment]
The method was added in https://github.com/nextcloud/server/commit/bd65f1ea283650d5ee52dc239aed8c4b00e82760 which is part of 28.0.0. You must be running a version lower than 28 as there is no other way to trigger this. Even if it would work then the file action wouldn't work as the files you had a massive overhaul in 28 with a completely new API that is used in this integration.

**Comment by miscawelo** [comment]
Got it, didn't know that. I'm running Nextcloud inside an Alpine container in the stable channel, current Nextcloud server version is 27.

I'll make sure my backups are up to date and will switch to the Edge branch which is on version 28. Thanks for the help!

**Comment by provokateurin** [comment]
Oh I just realized this is actually my mistake. I didn't intend to use this method as the app should work on all versions from 26 to 29. I'll fix this next week or so!

**Comment by miscawelo** [comment]
That's awesome, thanks a lot! If there's any way I can help with testing or whatever, let me know

**Comment by provokateurin** [comment]
Unfortunately I had to bump the minimum version to 28 because downgrading was not an option, but the fix has been released as v1.0.3.
