### ISSUE TITLE
Appstore release has broken download URL

### ISSUE THREAD

**Issue by Murguth** [nextcloud/integration_paperless#3]
Trying to download and install on a Synology Nextcloud instance, this is the error I get:

https://cloud.nextcloud.com/s/dwqb5tFBfTMoBb8/download/integration_paperless-1.0.0.tar.gz` resulted in a `404 Not Found` response: <!DOCTYPE html> <html class="ng-csp" data-placeholder-focus="false" lang="en" data-locale="en" translate="no" > <head (truncated...)

Some tip on my configuration:
Operating system: Linux 4.4.302+ x86_64
CPU: AMD Ryzen Embedded R1600 (4 cores)

Thank you.

**Comment by provokateurin** [comment]
@MB-Finski this looks really wrong, the release should be hosted on https://github.com/nextcloud-releases/integration_paperless

**Comment by MB-Finski** [comment]
Yeah that's true, sorry about this. I was just trying to get it up super quick for the demo so I manually built it. Had a brain fart while uploading it to the app store not realizing that the app store doesn't actually host the apps.

**Comment by MB-Finski** [comment]
I was meaning to fix this yesterday with the new release, but now I'm locked out already from company cloud and github.

**Comment by provokateurin** [comment]
Oh ok, I'll let the people know.

**Comment by MB-Finski** [comment]
I'm sorry about this Kate!

**Comment by provokateurin** [comment]
No problem :heart:

**Comment by Murguth** [comment]
Will you write something here when an update of the situation will be available?

Ty so much.

**Comment by Murguth** [comment]
No probs. I'm not in a hurry.

**Comment by github-cli** [comment]
mhh, looking forward to a paperless integration!

**Comment by provokateurin** [comment]
I'm working on it, I hope to release a working version tomorrow.

**Comment by github-cli** [comment]
Sounds good, what does the integration do?

**Comment by provokateurin** [comment]
For now it only adds a file action so you can upload a document from Nextcloud directly to paperless, but this can be easily extended to have more features (PRs welcome). For example I thought about exposing the documents in paperless as an external storage so you could browse all stored documents from within your Nextcloud including the tags etc. (and also search for files and so on)

**Comment by github-cli** [comment]
Would be cool…
I already have a flow set up so that all documents within a bunch of folders get automatically copied to the consume folder of paperless (with directory structure for automatic tags in paperless)
But that only works because Nextcloud has direct access to the consume folder.

being able to search and open documents within Nextcloud would be cool

**Comment by provokateurin** [comment]
Auto-upload is certainly something that could be implemented as well. Please open issues for those ideas, then they can be implemented at some point.

**Comment by provokateurin** [comment]
This problem is resolved in v1.0.1 which I just released to the Appstore.
