### ISSUE TITLE
Release for NC 30 

### ISSUE THREAD

**Issue by ArthFink** [nextcloud/integration_paperless#37]
Hey, 

i have just updated my NC server to version 30 and noticed that the Integration is not running.
Is there a specific reason for this?  

Thanks in advance

**Comment by provokateurin** [comment]
Hi, I'm sorry, this slipped past my radar.
I will make a release at the beginning of next week.
In the mean time you can force enable the app again, it is very likely compatible with Nextcloud 30 even though it doesn't advertise that yet.
